# Generated by Django 4.1.1 on 2022-10-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='ticker',
            new_name='pnr',
        ),
    ]
